- pkg/cli/iam_handle.go
- pkg/cli/iam_handle_test.go
> refactor: use limit reader to read request from file path

- apis/v1alpha1/iam_request_wrapper.go
- pkg/cli/iam_handle.go
- pkg/cli/iam_handle_test.go
- pkg/handler/iam_handler.go
- pkg/handler/iam_handler_test.go
- pkg/requestutil/request_test.go
> feat: add start time

- cmd/aod/main.go
- internal/version/version.go
- pkg/cli/root.go
- pkg/cli/root_test.go
> feat: add root command

- .github/workflows/ci.yml
- .github/workflows/iam-handle.yml
fix #19 
tested by trigger on push on branch
> feat: do workflow - IAM track

- .github/workflows/handle.yml
The condition check helps to skip time consuming steps when a PR is not AOD request.
> fix: add condition check in handle workflow

- .github/workflows/expire.yml
to match https://github.com/abcxyz/access-on-demand/blob/main/.github/workflows/handle.yml#L23
> fix: input style

- apis/v1alpha1/validation.go
- apis/v1alpha1/validation_test.go
> feat: validate cli request

- .github/workflows/cleanup.yml
hold until https://github.com/abcxyz/access-on-demand/pull/55 merges
> feat: aod cli cleanup workflow

- .github/workflows/cleanup.yml
- .github/workflows/expire.yml
- .github/workflows/handle.yml
- .github/workflows/validate.yml
- apis/v1alpha1/cli_request.go
- apis/v1alpha1/validation.go
- apis/v1alpha1/validation_test.go
- pkg/cli/cli_handle.go
- pkg/cli/root.go
- pkg/cli/root_test.go
- pkg/handler/cli_handler.go
- pkg/handler/cli_handler_test.go
> fix: aod cli subcommand

- .github/workflows/handle.yml
Fixes 57, to use this change, aod-template needs to add job permission `pull-requests: 'read'`
> fix: only handles IAM PR with required approval

- .github/workflows/handle.yml
> feat: add IAM PR comments

- .github/workflows/note.yml
> fix: pr note comment

- .github/workflows/handle.yml
> feat: add tool PR comments

- apis/v1alpha1/validation.go
- apis/v1alpha1/validation_test.go
- pkg/cli/iam_validate_test.go
- pkg/cli/tool_validate_test.go
> fix: catch empty request

- pkg/handler/iam_handler.go
- pkg/handler/iam_handler_test.go
> fix: ignore errors if error occured when removing expired iam

- pkg/cli/iam_handle.go
- pkg/cli/iam_handle_test.go
- pkg/cli/tool_base.go
- pkg/cli/tool_cleanup.go
- pkg/cli/tool_cleanup_test.go
- pkg/cli/tool_do.go
- pkg/cli/tool_do_test.go
- pkg/cli/util.go
- pkg/handler/tool_handler_test.go
> feat: output actions in cli

- .github/workflows/expire.yml
> feat: close the branch when pr is closed

- pkg/cli/iam_handle.go
- pkg/cli/iam_handle_test.go
- pkg/cli/tool_base.go
- pkg/cli/tool_cleanup_test.go
- pkg/cli/tool_do_test.go
- pkg/cli/util.go
- pkg/handler/tool_handler.go
- pkg/handler/tool_handler_test.go
> refactor: debug to verbose

- .github/workflows/handle.yml
- .github/workflows/tool_cleanup.yml
> feat: use cli outputs in pr comments

- .github/workflows/release.yml
- .goreleaser.yaml
> feat: add release

- .github/workflows/ci.yml
- test/integration/main_test.go
last part of #27 
Checked pantheon, binding was added and then removed.
> feat: add integ test workflow

- .github/workflows/expire.yml
> fix: changing pr start time for expire

- pkg/handler/iam_handler.go
- pkg/handler/iam_handler_test.go
> refactor: iam expire func

- pkg/cli/iam_cleanup.go
- pkg/cli/iam_cleanup_test.go
- pkg/cli/iam_handle.go
- pkg/cli/root.go
- pkg/cli/util.go
> feat: IAM cleanup cmd

- .github/workflows/ci.yml
release.yml needs to call ci wf.
> fix: add workflow_call trigger in ci

- .github/workflows/cleanup.yml
- .github/workflows/expire.yml
> fix: cleanup should be triggered when PR is automatically closed

- .github/workflows/cleanup.yml
> fix: delete branch no matter cleanup job's status since PR is closed

- pkg/handler/tool_handler.go
- pkg/handler/tool_handler_test.go
> fix: tool output executed commands

- .github/workflows/cleanup.yml
- .github/workflows/handle.yml
- .github/workflows/validate.yml
- docs/cli.md
> perf: use setup-binary action to improve binary install performance

- .github/workflows/cleanup.yml
upcoming part 2 - remove cli command.
> feat: remove tool cleanup part 1 - remove workflow

- apis/v1alpha1/tool_request.go
- apis/v1alpha1/validation.go
- apis/v1alpha1/validation_test.go
- pkg/cli/tool_validate_test.go
> feat: remove tool cleanup part 3 - update request definition

- pkg/requestutil/request.go
- pkg/requestutil/request_test.go
> fix: fail while unmarshal request with unknown fields

- .github/workflows/cleanup.yml
- .github/workflows/handle.yml
> chore: show error and output in both pr comments and terminal

- .github/workflows/cleanup.yml
- .github/workflows/handle.yml
tested here: https://github.com/abcxyz/aod-template/pull/91
> fix：cleanup workflow to query label info on the triggering pr
